-- ══════════════════════════════════════════════════════════════
--  STL_Mirror — Supabase Table & RLS & RPC Functions Setup
--  Run this in: Supabase Dashboard → SQL Editor
-- ══════════════════════════════════════════════════════════════

-- ── 1. Create Files Table if not exists ──────────────────────
CREATE TABLE IF NOT EXISTS public.files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text DEFAULT '',
  category text NOT NULL,
  original_filename text NOT NULL,
  file_name text NOT NULL UNIQUE,
  file_url text NOT NULL,
  file_extension text,
  mime_type text,
  file_size bigint NOT NULL,
  uploaded_by text DEFAULT 'admin',
  downloads integer DEFAULT 0 NOT NULL,
  views integer DEFAULT 0 NOT NULL,
  is_featured boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ── 2. Enable RLS on the files table ─────────────────────────
ALTER TABLE files ENABLE ROW LEVEL SECURITY;

-- ── 3. Drop any existing policies (clean slate) ──────────────
DROP POLICY IF EXISTS "Public can read files"    ON files;
DROP POLICY IF EXISTS "Admin can insert files"   ON files;
DROP POLICY IF EXISTS "Admin can update files"   ON files;
DROP POLICY IF EXISTS "Admin can delete files"   ON files;

-- ── 4. PUBLIC: Anyone (anon + logged-in) can SELECT files ─────
--    This lets regular visitors browse and download without logging in.
CREATE POLICY "Public can read files"
  ON files
  FOR SELECT
  USING (true);

-- ── 5. ADMIN ONLY: Only authenticated users can INSERT ────────
CREATE POLICY "Admin can insert files"
  ON files
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- ── 6. ADMIN ONLY: Only authenticated users can UPDATE ────────
CREATE POLICY "Admin can update files"
  ON files
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- ── 7. ADMIN ONLY: Only authenticated users can DELETE ────────
CREATE POLICY "Admin can delete files"
  ON files
  FOR DELETE
  TO authenticated
  USING (true);

-- ── 8. RPC Functions for Views/Downloads Counters ────────────
--    These allow the client to increment fields in the table
--    without requiring full update permissions (bypassing raw updates).

-- Function to increment views
CREATE OR REPLACE FUNCTION public.increment_views(file_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.files
  SET views = COALESCE(views, 0) + 1
  WHERE id = file_id;
END;
$$;

-- Function to increment downloads
CREATE OR REPLACE FUNCTION public.increment_downloads(file_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.files
  SET downloads = COALESCE(downloads, 0) + 1
  WHERE id = file_id;
END;
$$;
